### ISSUE TITLE
Does this will clean .scss files in node_modules?

### ISSUE THREAD

**Issue by jsu93** [tuananh/node-prune#1]

**Comment by tuananh** [comment]
no it doesn't . You can see the list of files it prune here https://github.com/tuananh/node-prune/blob/develop/prune.sh

**Comment by jsu93** [comment]
It will delete `assets` folder ? if so, please don't .
https://github.com/tuananh/node-prune/blob/cc4e919d8589ec95e1630e789ba9996bc9fab133/prune.sh#L45
